name: PR Closed Workflow

on:
  pull_request:
    types: [closed]

env:
  HaT_TOKEN: ${{ secrets.HaT_TOKEN }}

jobs:
  clean-up-test-space:
    name: Cleanup Contentful Test Space
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/production' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine file name
        id: calculate_file_name
        run: |
          filename="${{ github.ref }}.txt"
          filename="${filename//\//_}"
          echo "filename=$filename" >> $GITHUB_OUTPUT
      - name: Download all artifacts and get artifact id
        id: download_artifacts
        run: |
          output=$( curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/contentful/marketplace-partner-apps/actions/artifacts | \
            jq -r '.artifacts | .[] | select(.name == "${{steps.calculate_file_name.outputs.filename}}") | .id' | head -n 1 )
          echo $output
          echo "artifact_id=$output" >> $GITHUB_OUTPUT
      - name: Fetch artifact by artfact_id
        id: fetch_artifact
        run: |
          output=$( curl -o archive.zip -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/contentful/marketplace-partner-apps/actions/artifacts/${{steps.download_artifacts.outputs.artifact_id}}/zip)
          echo $output
          echo "file=$output" >> $GITHUB_OUTPUT
      - name: Unzip and Read File
        id: unzip_and_read_file
        run: |
          unzip archive.zip
          cat ${{steps.calculate_file_name.outputs.filename}}
          echo "space_id=$(cat ${{steps.calculate_file_name.outputs.filename}})" >> $GITHUB_OUTPUT
      - name: Delete Contentful Test Space
        id: delete_test_space
        run: |
          curl --request DELETE \
            --url 'https://api.contentful.com/spaces/${{steps.unzip_and_read_file.outputs.space_id}}' \
            --header 'Authorization: Bearer ${{ secrets.HAT_TOKEN }}' \
            --header 'Content-Type: application/vnd.contentful.management.v1+json'
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :boom: Test environment at https://app.contentful.com/${{steps.unzip_and_read_file.outputs.space_id}}/ has been deleted :boom:
