name: CI

on:
  push:
    branches: ['main', 'production']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, Test, Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DEFINITIONS_ORG_ID: ${{ secrets.DEFINITIONS_ORG_ID }}
      CONTENTFUL_CMA_TOKEN: ${{ secrets.CONTENTFUL_CMA_TOKEN }}
      TEST_ORG_ID: ${{ secrets.TEST_ORG_ID }}
      TEST_CMA_TOKEN: ${{ secrets.TEST_CMA_TOKEN }}
    steps:
      - name: Check out code for target branch
        run: git checkout origin/main
      - name: Check out code for source branch
        uses: actions/checkout@v3
        with:
          ref: ${GITHUB_REF}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Base ref
        run: echo ${{ github.event.pull_request.base.ref }}
      - name: Head ref
        run: echo ${GITHUB_REF}
      - name: Job workflow
        run: echo ${{ github.job_workflow_sha }}
      - name: Print main package-lock hash
        run: echo ${{ hashFiles('**/package-lock.json') }}
      - name: Root dependencies
        run: npm install
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: App dependencies
        run: npm run install-apps
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Deploy Staging
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm run deploy:staging
      - name: Deploy Production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: npm run deploy
